# https://github.com/Homebrew/homebrew-bundle

cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/fonts"
tap "getantibody/tap"

# languages
brew "node"
# python refers to python 3
# https://docs.brew.sh/Homebrew-and-Python
brew "python"
brew "python@2"
brew "ruby"

# tools
brew "getantibody/tap/antibody"
brew "bash"
brew "bat"
# For YouCompleteMe
brew "cmake"
brew "ctop"
brew "diff-so-fancy"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "glances"
brew "gpg"
brew "htop"
brew "jq"
brew "md5sha1sum"
brew "mosh", args: ['HEAD']
brew "neofetch"
brew "pandoc"
# for entering a GPG passphrase
brew "pinentry-mac"
brew "ripgrep"
brew "shellcheck"
brew "tldr"
brew "tmux"
brew "tokei"
brew "xsv"
brew "vim"
brew "yarn"
brew "zsh"

# applications
cask "alfred"
cask "android-studio"
# cask "appcleaner"
cask "anki"
cask "docker"
cask "dropbox"
cask "duet"
cask "evernote"
cask "font-source-code-pro"
cask "homebrew/cask-versions/firefox-developer-edition"
# cask "gimp"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
# cask "kap"
cask "karabiner-elements"
cask "keybase"
cask "obs"
# cask "paintbrush"
# cask "razer-synapse"
cask "smcfancontrol"
cask "spectacle"
cask "steam"
cask "sublime-text"
mas 'Todoist', id: 585829637
cask "visual-studio-code"
cask "vlc"
